import yfinance as yf
import pandas as pd
import numpy as np
import pandas_ta as ta
import nltk
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

def get_news_sentiment(ticker_symbol: str) -> float:
    try:
        news_data = yf.Ticker(ticker_symbol).news
        if not news_data:
            return 0.0
            
        analyzer = SentimentIntensityAnalyzer()
        scores = []
        for item in news_data:
            content = item.get('content', {})
            title = content.get('title', '') if isinstance(content, dict) else item.get('title', '')
            if title:
                scores.append(analyzer.polarity_scores(title)['compound'])
                
        if not scores:
            return 0.0
            
        return float(np.mean(scores))
    except Exception as e:
        print(f"Error fetching sentiment for {ticker_symbol}: {e}")
        return 0.0

class DataOrchestrator:
    def __init__(self):
        """Initialize the DataOrchestrator."""
        pass

    def fetch_data(
        self,
        ticker: str,
        start_date: str,
        end_date: str,
    ) -> pd.DataFrame:
        """
        Fetch historical OHLCV data from Yahoo Finance.

        Args:
            ticker:     Stock ticker symbol (e.g., 'AAPL')
            start_date: Start date in 'YYYY-MM-DD' format
            end_date:   End date in 'YYYY-MM-DD' format

        Returns:
            pd.DataFrame: DataFrame containing historical OHLCV data
        """
        print(f"Fetching data for {ticker} from {start_date} to {end_date}...")
        df = yf.download(
            ticker,
            start=start_date,
            end=end_date,
            auto_adjust=True,
            threads=False,    # avoid thread-pool hangs on cloud servers
            progress=False,   # suppress progress bar output
        )
        if df.empty:
            raise ValueError(f"No data found for {ticker} in the given date range.")
        return df

    def add_features(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Add technical indicators and features to the dataframe.
        
        Args:
            df: Input dataframe with OHLCV data
            
        Returns:
            pd.DataFrame: DataFrame with additional technical indicators and NaN values removed
        """
        print("Adding technical features...")
        df = df.copy()

        # Flatten MultiIndex columns (newer yfinance versions)
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)

        # Normalise column names
        df.columns = [str(c).strip().title() for c in df.columns]

        if "Close" not in df.columns:
            raise ValueError("The dataframe does not contain a 'Close' column.")

        # Append technical indicators using pandas_ta strategy
        df.ta.bbands(length=20, std=2, append=True)
        df.ta.atr(length=14, append=True)
        df.ta.rsi(length=14, append=True)
        df.ta.macd(fast=12, slow=26, signal=9, append=True)
        df.ta.obv(append=True)

        # Log Returns
        close  = df["Close"]
        df["Log_Returns"] = np.log(close / close.shift(1))

        # Drop NaN rows from rolling-window warm-up
        print("Dropping NaN values generated by technical indicators...")
        df.dropna(inplace=True)

        return df

    def process(
        self,
        ticker: str,
        start_date: str,
        end_date: str,
        display_currency: str = 'Native',
    ) -> tuple[pd.DataFrame, pd.Series, pd.DataFrame, str, list]:
        """
        Execute the full data ingestion and feature engineering pipeline.
        """
        df = self.fetch_data(ticker, start_date, end_date)
        
        # Flatten columns early so we can safely mutate Open/High/Low/Close and join correctly
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)
        df.columns = [str(c).strip().title() for c in df.columns]
        
        print("Fetching news sentiment via Yahoo Finance...")
        live_sentiment = get_news_sentiment(ticker)
        
        # Strip timezones from both indices to prevent tz-naive / tz-aware clash
        df.index = df.index.tz_localize(None) if df.index.tz is not None else df.index
        
        top_headlines = []
        try:
            news_data = yf.Ticker(ticker).news
            for item in news_data[:5]:
                content = item.get('content', {})
                t = content.get('title', '') if isinstance(content, dict) else item.get('title', '')
                if t: top_headlines.append(t)
        except Exception:
            pass

        base_currency = yf.Ticker(ticker).info.get('currency', 'USD')
        if base_currency is None:
            base_currency = 'USD'
            
        currency_code = base_currency if display_currency == 'Native' else display_currency

        if display_currency != 'Native' and display_currency != base_currency:
            fx_ticker = f"{base_currency}{display_currency}=X"
            print(f"Fetching FX rate for {fx_ticker}...")
            try:
                fx_data = yf.download(fx_ticker, period="1d", progress=False)
                if not fx_data.empty:
                    if isinstance(fx_data.columns, pd.MultiIndex):
                        fx_data.columns = fx_data.columns.get_level_values(0)
                    fx_data.columns = [str(c).strip().title() for c in fx_data.columns]
                    
                    fx_rate = float(fx_data['Close'].iloc[-1])
                    print(f"Applying FX rate {fx_rate} to price columns...")
                    for col in ["Open", "High", "Low", "Close", "Adj Close"]:
                        if col in df.columns:
                            df[col] = df[col] * fx_rate
            except Exception as e:
                print(f"Could not convert currency: {e}")
                currency_code = base_currency

        # The add_features method also contains flatten column logic, which is fine to run twice
        df_featured = self.add_features(df)
        
        # Target Shift: strictly shift the Close price backward by one day
        df_featured['Target_Next_Close'] = df_featured['Close'].shift(-1)
        
        # Vectorized Assignment: initialize historical rows to 0.0 to prevent look-ahead bias
        df_featured['Sentiment_Score'] = 0.0
        
        # The inference row assignment
        df_featured.iloc[-1, df_featured.columns.get_loc('Sentiment_Score')] = live_sentiment
        
        # The Inference Row: extract the single row for today's data where Target_Next_Close is NaN
        X_inference = df_featured.iloc[[-1]].copy()
        
        # Drop NaNs for Training: remove rows with missing targets or missing rolling features
        df_featured.dropna(inplace=True)
        
        y_train = df_featured['Target_Next_Close']
        X_train = df_featured.drop(columns=['Target_Next_Close'])
        X_inference = X_inference.drop(columns=['Target_Next_Close'])
        
        return X_train, y_train, X_inference, currency_code, top_headlines
