import yfinance as yf
import pandas as pd
import numpy as np
import ta
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

try:
    nltk.download('vader_lexicon', quiet=True)
except Exception:
    pass

def get_news_sentiment(ticker: str) -> tuple[pd.DataFrame, list[str]]:
    try:
        news_data = yf.Ticker(ticker).news
        
        if not news_data:
            return pd.DataFrame(columns=['Sentiment']), []
        
        vader = SentimentIntensityAnalyzer()
        parsed_data = []
        top_headlines = []
        
        for item in news_data:
            content = item.get('content', {})
            title   = content.get('title', '') if isinstance(content, dict) else item.get('title', '')
            if not title:
                continue
            
            top_headlines.append(title)
            
            pub_date = content.get('pubDate', '') if isinstance(content, dict) else item.get('providerPublishTime', '')
            try:
                date = pd.to_datetime(pub_date, unit='s' if isinstance(pub_date, (int, float)) else None).normalize()
            except Exception:
                date = pd.Timestamp.today().normalize()
            
            score = vader.polarity_scores(title)['compound']
            parsed_data.append({'Date': date, 'Sentiment': score})
        
        if not parsed_data:
            return pd.DataFrame(columns=['Sentiment']), []
        
        df = pd.DataFrame(parsed_data)
        df['Date'] = pd.to_datetime(df['Date'])
        daily_sentiment = df.groupby('Date')['Sentiment'].mean()
        daily_sentiment.index = pd.to_datetime(daily_sentiment.index)
        
        return daily_sentiment.to_frame(), top_headlines[:5]
        
    except Exception as e:
        print(f"Error fetching sentiment for {ticker}: {e}")
        
    return pd.DataFrame(columns=['Sentiment']), []

class DataOrchestrator:
    def __init__(self):
        """Initialize the DataOrchestrator."""
        pass

    def fetch_data(self, ticker: str, start_date: str, end_date: str) -> pd.DataFrame:
        """
        Fetch historical OHLCV data from Yahoo Finance.
        
        Args:
            ticker: Stock ticker symbol (e.g., 'AAPL')
            start_date: Start date in 'YYYY-MM-DD' format
            end_date: End date in 'YYYY-MM-DD' format
            
        Returns:
            pd.DataFrame: DataFrame containing historical OHLCV data
        """
        print(f"Fetching data for {ticker} from {start_date} to {end_date}...")
        df = yf.download(ticker, start=start_date, end=end_date, auto_adjust=True)
        if df.empty:
            raise ValueError(f"No data found for {ticker} in the given date range.")
        return df

    def add_features(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Add technical indicators and features to the dataframe.
        
        Args:
            df: Input dataframe with OHLCV data
            
        Returns:
            pd.DataFrame: DataFrame with additional technical indicators and NaN values removed
        """
        print("Adding technical features...")
        df = df.copy()

        # Flatten MultiIndex columns (newer yfinance versions)
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)

        # Normalise column names
        df.columns = [str(c).strip().title() for c in df.columns]

        if "Close" not in df.columns:
            raise ValueError("The dataframe does not contain a 'Close' column.")

        close  = df["Close"]
        high   = df["High"]
        low    = df["Low"]

        # 1. SMA (20-period)
        df["SMA_20"] = ta.trend.sma_indicator(close, window=20)

        # 2. RSI (14-period)
        df["RSI_14"] = ta.momentum.rsi(close, window=14)

        # 3. MACD
        macd_obj = ta.trend.MACD(close)
        df["MACD_12_26_9"]  = macd_obj.macd()
        df["MACDh_12_26_9"] = macd_obj.macd_diff()
        df["MACDs_12_26_9"] = macd_obj.macd_signal()

        # 4. Bollinger Bands
        bb = ta.volatility.BollingerBands(close, window=20, window_dev=2)
        df["BBL_20_2"] = bb.bollinger_lband()
        df["BBM_20_2"] = bb.bollinger_mavg()
        df["BBU_20_2"] = bb.bollinger_hband()
        df["BBB_20_2"] = bb.bollinger_wband()
        df["BBP_20_2"] = bb.bollinger_pband()

        # 5. Log Returns
        df["Log_Returns"] = np.log(close / close.shift(1))

        # Drop NaN rows from rolling-window warm-up
        print("Dropping NaN values generated by technical indicators...")
        df.dropna(inplace=True)

        return df

    def process(self, ticker: str, start_date: str, end_date: str, display_currency: str = 'Native') -> tuple[pd.DataFrame, str, list[str]]:
        """
        Execute the full data ingestion and feature engineering pipeline.
        """
        df = self.fetch_data(ticker, start_date, end_date)
        
        # Flatten columns early so we can safely mutate Open/High/Low/Close and join correctly
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)
        df.columns = [str(c).strip().title() for c in df.columns]
        
        # Merge sentiment
        print("Fetching news sentiment via Yahoo Finance...")
        sentiment_df, top_headlines = get_news_sentiment(ticker)
        
        # Strip timezones from both indices to prevent tz-naive / tz-aware clash
        df.index = df.index.tz_localize(None) if df.index.tz is not None else df.index
        
        if not sentiment_df.empty:
            sentiment_df.index = sentiment_df.index.tz_localize(None) if sentiment_df.index.tz is not None else sentiment_df.index
            df = df.join(sentiment_df, how='left')
            df['Sentiment'] = df['Sentiment'].fillna(0.0)
        else:
            df['Sentiment'] = 0.0

        base_currency = yf.Ticker(ticker).info.get('currency', 'USD')
        if base_currency is None:
            base_currency = 'USD'
            
        currency_code = base_currency if display_currency == 'Native' else display_currency

        if display_currency != 'Native' and display_currency != base_currency:
            fx_ticker = f"{base_currency}{display_currency}=X"
            print(f"Fetching FX rate for {fx_ticker}...")
            try:
                fx_data = yf.download(fx_ticker, period="1d", progress=False)
                if not fx_data.empty:
                    if isinstance(fx_data.columns, pd.MultiIndex):
                        fx_data.columns = fx_data.columns.get_level_values(0)
                    fx_data.columns = [str(c).strip().title() for c in fx_data.columns]
                    
                    fx_rate = float(fx_data['Close'].iloc[-1])
                    print(f"Applying FX rate {fx_rate} to price columns...")
                    for col in ["Open", "High", "Low", "Close", "Adj Close"]:
                        if col in df.columns:
                            df[col] = df[col] * fx_rate
            except Exception as e:
                print(f"Could not convert currency: {e}")
                currency_code = base_currency

        # The add_features method also contains flatten column logic, which is fine to run twice
        df_featured = self.add_features(df)
        return df_featured, currency_code, top_headlines
